### ISSUE TITLE
Parsing cmdline arguments: S30cmdline: PANIC: -1: invalid number

### ISSUE THREAD

**Issue by vt-alt** [legionus/make-initrd#1]
Параметр ядра `panic=-1` конфликтует с initrd параметром PANIC типа number.

> Parsing cmdline arguments: S30cmdline: PANIC: -1: invalid number

При этом `-1` разрешенное значение для ядра.

**Comment by legionus** [comment]
https://github.com/torvalds/linux/blob/619e17cf75dd58905aa67ccd494a6ba5f19d6cc6/Documentation/admin-guide/kernel-parameters.txt#L3244-L3249

**Comment by legionus** [comment]
Fixed in master

**Comment by vt-alt** [comment]
Thanks.
